# Generated by Django 6.0.3 on 2026-03-18 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('custom_lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Romantic', 'Romantic'), ('Energetic', 'Energetic'), ('Calm', 'Calm')], max_length=20)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('HipHop', 'HipHop')], max_length=20)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Graduation', 'Graduation'), ('Anniversary', 'Anniversary'), ('Custom', 'Custom')], max_length=20)),
                ('voice_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Child', 'Child'), ('Choir', 'Choir'), ('Instrumental', 'Instrumental'), ('Duet', 'Duet')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='core.song')),
            ],
            options={
                'verbose_name': 'Share Link',
            },
        ),
        migrations.CreateModel(
            name='MusicGenerationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('custom_lyrics', models.TextField(blank=True, null=True)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Graduation', 'Graduation'), ('Anniversary', 'Anniversary'), ('Custom', 'Custom')], max_length=20)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('HipHop', 'HipHop')], max_length=20)),
                ('voice_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Child', 'Child'), ('Choir', 'Choir'), ('Instrumental', 'Instrumental'), ('Duet', 'Duet')], max_length=20)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Romantic', 'Romantic'), ('Energetic', 'Energetic'), ('Calm', 'Calm')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_retry', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_request', to='core.song')),
            ],
            options={
                'verbose_name': 'Music Generation Request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
