# Generated by Django 6.0.3 on 2026-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
