# Generated by Django 6.0.3 on 2026-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
